# Database backend settings
DATABASES = {
    'default': {
        # Replace 'sqlite3' with 'postgresql' or 'mysql'.
        # 'ENGINE': 'django.db.backends.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        # Database name or path to database file if using sqlite3.
        # 'NAME': working_path('dbs/pootle.db'),
        'NAME': 'pootledb',
        # Not used with sqlite3.
        # 'USER': '',
        'USER': 'pootle',
        # Not used with sqlite3.
        # 'PASSWORD': '',
        'PASSWORD': 'x2vv5YbYjyOL16vrR504pdjJz+bJd5R0',
        # Set to empty string for localhost. Not used with sqlite3.
        # 'HOST': '',
        'HOST': '127.0.0.1',
        # Set to empty string for default. Not used with sqlite3.
        'PORT': '',
        # See https://docs.djangoproject.com/en/1.10/topics/db/transactions/
        # required for Django + sqlite
        'ATOMIC_REQUESTS': True
        }}